apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "perf-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "perf-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "perf-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "perf-agent.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "perf-agent.serviceAccountName" . }}
      hostPID: {{ .Values.hostPID }}
      containers:
        - name: perf-agent
          image: {{ include "perf-agent.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: health
              containerPort: {{ .Values.health.port }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
